# Data Scraping
---

<div class="alert alert-block alert-danger">
<b>Warning:</b> Do not change this script.
</div>

In [1]:
# Import libraries
import csv
import pandas as pd
from tqdm.notebook import tqdm
import snscrape.modules.twitter as sntwitter

In [ ]:
path = "/home/jupyter/agra/source code/sentiment analytics/"

In [2]:
# input keyword
keyword = '@Kopikenangan_ID OR Kopi Kenangan OR #FromMantanToUnicorn'

In [3]:
# input date
scraper = sntwitter.TwitterSearchScraper(keyword + 'since:2022-01-01 until:2023-01-01')

In [4]:
# start scraping data
tweets = []
maxTweets = 10_000
for i,tweet in tqdm(enumerate(scraper.get_items()), total=maxTweets) :
    data = [
        tweet.date,
        tweet.id, 
        tweet.rawContent, 
        tweet.user.username, 
        tweet.user.verified, 
        tweet.user.followersCount, 
        tweet.user.friendsCount, 
        tweet.mentionedUsers, 
        tweet.replyCount, 
        tweet.retweetCount, 
        tweet.likeCount, 
        tweet.media, 
        tweet.lang, 
        tweet.user.location
    ]
    
    tweets.append(data)
    
    if i > maxTweets:
        break

  0%|          | 0/10000 [00:00<?, ?it/s]

In [5]:
# create df
tweet_df = pd.DataFrame(
    tweets,columns=['date', 
                    'tweet_id', 
                    'text', 
                    'username', 
                    'verified', 
                    'followers',
                    'following',
                    'mentioned users',
                    'retweet',
                    'like ', 
                    'reply', 
                    'media', 
                    'language', 
                    'location'] 
)

In [6]:
# save to csv
tweet_df.to_csv(path + 'data/resto-scrape.csv', index = False)

In [8]:
tweet_df

,date,tweet_id,text,username,verified,followers,following,mentioned users,retweet,like,reply,media,language,location
0,2022-12-31 23:52:16+00:00,1609336667881570306,"Pickup #kopi , tetap buka meski tanggal libur ...",yussanid,False,384,424,None,0,0,0,None,in,Yogyakarta dari Ponorogo
1,2022-12-31 22:55:45+00:00,1609322447274377218,@tanyarlfes Part time di kopi kenangan aja ada...,indilaw6,False,211,187,[https://twitter.com/tanyarlfes],1,0,0,None,in,dimana
2,2022-12-31 17:50:58+00:00,1609245745131192323,"aku tadi keliling"" naik motor sambil dengerin ...",mimowy,False,4,230,None,0,0,0,None,in,
3,2022-12-31 17:12:53+00:00,1609236161129742338,"wah, kopi kenangan nya sudah selesai. Makasih ...",rynthings,False,9,300,None,0,0,0,None,in,"Paris, France"
4,2022-12-31 16:20:04+00:00,1609222868226945024,Menutup tahun dengan kenangan.\nKopi kenangan ...,answer_ksj,False,160,296,None,0,0,0,[Photo(previewUrl='https://pbs.twimg.com/media...,in,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9997,2022-08-02 00:31:21+00:00,1554263547034472448,@bumblesupremacy Kopi kenangan enak tuh di grab,hansoctv,False,485,248,[https://twitter.com/bumblesupremacy],0,0,0,None,in,
9998,2022-08-01 23:34:09+00:00,1554249153206960128,Awali pagi hari mu dengan se cangkir kopi hita...,biasaajaseh,False,241,358,None,0,0,0,None,in,"Malang, Jawa Timur"
9999,2022-08-01 23:10:23+00:00,1554243174478282752,"Kopi yang pahit bisa meninggalkan ketenangan ,...",lutfiibrahim60,False,0,9,None,0,0,0,None,in,
10000,2022-08-01 23:03:43+00:00,1554241493598347264,"ahaha valid bgt nih😭 bikin bingung gaksi, haru...",HikmahWachyudi1,False,544,187,None,0,0,0,None,in,"Jawa Tengah, Indonesia"
10001,2022-08-01 22:54:51+00:00,1554239263218475008,@thvvrichi Kopi kenangan mantan pasti haha,mimiyathv,False,184,251,[https://twitter.com/thvvrichi],0,0,0,None,in,bangtan sonyeondan ♡